version: '3'

services:

  redis:
    image: redis:alpine
    networks:
      - live

  web:
    build: ./project
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    environment:
      DEBUG: "True"
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
    links:
      - redis
    depends_on:
      - redis
    networks:
      - live
      
  celery:
    build: ./project
    command: celery -A myceleryproject worker -l info
    environment:
      DEBUG: "True"
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
    links:
      - redis
    depends_on:
      - redis
    networks:
      - live

  celery-beat:
    build: ./project
    command: celery -A myceleryproject beat -l info
    environment:
      DEBUG: "True"
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
    links:
      - celery
      - redis
    depends_on:
      - celery
      - redis
    networks:
      - live

networks:
  live:
